
GET http://localhost:3000/User

###
POST http://localhost:3000/User/64132129bb0f147ba2b09136
Content-Type: application/json

{
    "username":"Usere",
    "location":"Mogappair East",
    "pickup":"20/01/2020",
    "return":"20/02/2020",
    "pay":"2000"
}

###
GET http://localhost:3000/Users/64132129bb0f147ba2b09136
###
POST  http://localhost:3000/User
Content-Type: application/json

{
    "username":"Usere",
    "password": "i2rhg92",
    "email": "Usere@gmail.com",
    "phone": "7879954559"
}

###
DELETE http://localhost:3000/User/63a89dee212d9856d647246f

###

PATCH  http://localhost:3000/User/303

###########################################################################

###

GET http://localhost:3000/Rent

###

POST http://localhost:3000/Rent
Content-Type: application/json

{
    "location":"Koyembedu",
    "pickup": "2023-01-04",
    "return": "2023-01-11",
    "pay":"7000"
}

###

DELETE http://localhost:3000/Rent/63a69844c1b27a9b82215dc9

###

PATCH http://localhost:3000/Rent/63a69844c1b27a9b82215dc9
Content-Type: application/json

{
    "name":"User1"
}
